Repository chingu-voyages/ChinguResourceList, pull requests merged in 2020-10, with the labels that each got.

#14 Feature/add code snippets
  README.md
  codesnippets/reduceObject.js
Labels: documentation

#15 Promote the addition of the Code Snippets feature
  README.md
  codesnippets/reduceObject.js
Labels: documentation

#17 Feature: Add code snippets & articles
  README.md
  codesnippets/formatRawDate.js
  codesnippets/objectToFile.js
  codesnippets/validateDirPath.js
Labels: documentation

#16 docs: added deployment section
  README.md
Labels: documentation, hacktoberfest-accepted

#19 Promote changes staged in the `development` branch
  README.md
  codesnippets/formatRawDate.js
  codesnippets/objectToFile.js
  codesnippets/validateDirPath.js
Labels: documentation, hacktoberfest-accepted

#21 Update README.md
  README.md
Labels: hacktoberfest-accepted

#20 Update README.md
  README.md
Labels: hacktoberfest-accepted

#22 Feature: Add MS JS Beginners Course
  README.md
Labels: documentation

#23 Promote changes
  README.md
Labels: hacktoberfest-accepted

#24 Merge all approved changes
  README.md
Labels: documentation

#25 Feature/css resources
  README.md
Labels: documentation, hacktoberfest-accepted

#26 Add Javascript Resources
  README.md
Labels: documentation, hacktoberfest-accepted

#27 Merge latest changes into production
  README.md
Labels: documentation

#28 Add GitExplorer
  README.md
Labels: documentation, hacktoberfest-accepted

#30 Add assorted resources
  README.md
Labels: hacktoberfest-accepted
